name: kang_cuci
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^7.8.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  firebase_core: ^2.16.0
  equatable: ^2.0.5
  cloud_firestore: ^4.9.2
  injectable: ^2.3.0
  get_it: ^7.6.4
  dev: ^1.0.0
  injectable_generator: ^2.4.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  shimmer: ^3.0.0
  firebase_auth: ^4.10.0
  google_sign_in: ^6.1.5
  flutter_easyloading: ^3.0.5

dev_dependencies:  
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/